#if 0
#elif defined(__arm64__) && __arm64__
// Generated by Apple Swift version 6.0.2 effective-5.10 (swiftlang-6.0.2.1.2 clang-1600.0.26.4)
#ifndef CLEVERADSSOLUTIONS_SWIFT_H
#define CLEVERADSSOLUTIONS_SWIFT_H
#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wgcc-compat"

#if !defined(__has_include)
# define __has_include(x) 0
#endif
#if !defined(__has_attribute)
# define __has_attribute(x) 0
#endif
#if !defined(__has_feature)
# define __has_feature(x) 0
#endif
#if !defined(__has_warning)
# define __has_warning(x) 0
#endif

#if __has_include(<swift/objc-prologue.h>)
# include <swift/objc-prologue.h>
#endif

#pragma clang diagnostic ignored "-Wauto-import"
#if defined(__OBJC__)
#include <Foundation/Foundation.h>
#endif
#if defined(__cplusplus)
#include <cstdint>
#include <cstddef>
#include <cstdbool>
#include <cstring>
#include <stdlib.h>
#include <new>
#include <type_traits>
#else
#include <stdint.h>
#include <stddef.h>
#include <stdbool.h>
#include <string.h>
#endif
#if defined(__cplusplus)
#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wnon-modular-include-in-framework-module"
#if defined(__arm64e__) && __has_include(<ptrauth.h>)
# include <ptrauth.h>
#else
#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wreserved-macro-identifier"
# ifndef __ptrauth_swift_value_witness_function_pointer
#  define __ptrauth_swift_value_witness_function_pointer(x)
# endif
# ifndef __ptrauth_swift_class_method_pointer
#  define __ptrauth_swift_class_method_pointer(x)
# endif
#pragma clang diagnostic pop
#endif
#pragma clang diagnostic pop
#endif

#if !defined(SWIFT_TYPEDEFS)
# define SWIFT_TYPEDEFS 1
# if __has_include(<uchar.h>)
#  include <uchar.h>
# elif !defined(__cplusplus)
typedef uint_least16_t char16_t;
typedef uint_least32_t char32_t;
# endif
typedef float swift_float2  __attribute__((__ext_vector_type__(2)));
typedef float swift_float3  __attribute__((__ext_vector_type__(3)));
typedef float swift_float4  __attribute__((__ext_vector_type__(4)));
typedef double swift_double2  __attribute__((__ext_vector_type__(2)));
typedef double swift_double3  __attribute__((__ext_vector_type__(3)));
typedef double swift_double4  __attribute__((__ext_vector_type__(4)));
typedef int swift_int2  __attribute__((__ext_vector_type__(2)));
typedef int swift_int3  __attribute__((__ext_vector_type__(3)));
typedef int swift_int4  __attribute__((__ext_vector_type__(4)));
typedef unsigned int swift_uint2  __attribute__((__ext_vector_type__(2)));
typedef unsigned int swift_uint3  __attribute__((__ext_vector_type__(3)));
typedef unsigned int swift_uint4  __attribute__((__ext_vector_type__(4)));
#endif

#if !defined(SWIFT_PASTE)
# define SWIFT_PASTE_HELPER(x, y) x##y
# define SWIFT_PASTE(x, y) SWIFT_PASTE_HELPER(x, y)
#endif
#if !defined(SWIFT_METATYPE)
# define SWIFT_METATYPE(X) Class
#endif
#if !defined(SWIFT_CLASS_PROPERTY)
# if __has_feature(objc_class_property)
#  define SWIFT_CLASS_PROPERTY(...) __VA_ARGS__
# else
#  define SWIFT_CLASS_PROPERTY(...) 
# endif
#endif
#if !defined(SWIFT_RUNTIME_NAME)
# if __has_attribute(objc_runtime_name)
#  define SWIFT_RUNTIME_NAME(X) __attribute__((objc_runtime_name(X)))
# else
#  define SWIFT_RUNTIME_NAME(X) 
# endif
#endif
#if !defined(SWIFT_COMPILE_NAME)
# if __has_attribute(swift_name)
#  define SWIFT_COMPILE_NAME(X) __attribute__((swift_name(X)))
# else
#  define SWIFT_COMPILE_NAME(X) 
# endif
#endif
#if !defined(SWIFT_METHOD_FAMILY)
# if __has_attribute(objc_method_family)
#  define SWIFT_METHOD_FAMILY(X) __attribute__((objc_method_family(X)))
# else
#  define SWIFT_METHOD_FAMILY(X) 
# endif
#endif
#if !defined(SWIFT_NOESCAPE)
# if __has_attribute(noescape)
#  define SWIFT_NOESCAPE __attribute__((noescape))
# else
#  define SWIFT_NOESCAPE 
# endif
#endif
#if !defined(SWIFT_RELEASES_ARGUMENT)
# if __has_attribute(ns_consumed)
#  define SWIFT_RELEASES_ARGUMENT __attribute__((ns_consumed))
# else
#  define SWIFT_RELEASES_ARGUMENT 
# endif
#endif
#if !defined(SWIFT_WARN_UNUSED_RESULT)
# if __has_attribute(warn_unused_result)
#  define SWIFT_WARN_UNUSED_RESULT __attribute__((warn_unused_result))
# else
#  define SWIFT_WARN_UNUSED_RESULT 
# endif
#endif
#if !defined(SWIFT_NORETURN)
# if __has_attribute(noreturn)
#  define SWIFT_NORETURN __attribute__((noreturn))
# else
#  define SWIFT_NORETURN 
# endif
#endif
#if !defined(SWIFT_CLASS_EXTRA)
# define SWIFT_CLASS_EXTRA 
#endif
#if !defined(SWIFT_PROTOCOL_EXTRA)
# define SWIFT_PROTOCOL_EXTRA 
#endif
#if !defined(SWIFT_ENUM_EXTRA)
# define SWIFT_ENUM_EXTRA 
#endif
#if !defined(SWIFT_CLASS)
# if __has_attribute(objc_subclassing_restricted)
#  define SWIFT_CLASS(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) __attribute__((objc_subclassing_restricted)) SWIFT_CLASS_EXTRA
#  define SWIFT_CLASS_NAMED(SWIFT_NAME) __attribute__((objc_subclassing_restricted)) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
# else
#  define SWIFT_CLASS(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
#  define SWIFT_CLASS_NAMED(SWIFT_NAME) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
# endif
#endif
#if !defined(SWIFT_RESILIENT_CLASS)
# if __has_attribute(objc_class_stub)
#  define SWIFT_RESILIENT_CLASS(SWIFT_NAME) SWIFT_CLASS(SWIFT_NAME) __attribute__((objc_class_stub))
#  define SWIFT_RESILIENT_CLASS_NAMED(SWIFT_NAME) __attribute__((objc_class_stub)) SWIFT_CLASS_NAMED(SWIFT_NAME)
# else
#  define SWIFT_RESILIENT_CLASS(SWIFT_NAME) SWIFT_CLASS(SWIFT_NAME)
#  define SWIFT_RESILIENT_CLASS_NAMED(SWIFT_NAME) SWIFT_CLASS_NAMED(SWIFT_NAME)
# endif
#endif
#if !defined(SWIFT_PROTOCOL)
# define SWIFT_PROTOCOL(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) SWIFT_PROTOCOL_EXTRA
# define SWIFT_PROTOCOL_NAMED(SWIFT_NAME) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_PROTOCOL_EXTRA
#endif
#if !defined(SWIFT_EXTENSION)
# define SWIFT_EXTENSION(M) SWIFT_PASTE(M##_Swift_, __LINE__)
#endif
#if !defined(OBJC_DESIGNATED_INITIALIZER)
# if __has_attribute(objc_designated_initializer)
#  define OBJC_DESIGNATED_INITIALIZER __attribute__((objc_designated_initializer))
# else
#  define OBJC_DESIGNATED_INITIALIZER 
# endif
#endif
#if !defined(SWIFT_ENUM_ATTR)
# if __has_attribute(enum_extensibility)
#  define SWIFT_ENUM_ATTR(_extensibility) __attribute__((enum_extensibility(_extensibility)))
# else
#  define SWIFT_ENUM_ATTR(_extensibility) 
# endif
#endif
#if !defined(SWIFT_ENUM)
# define SWIFT_ENUM(_type, _name, _extensibility) enum _name : _type _name; enum SWIFT_ENUM_ATTR(_extensibility) SWIFT_ENUM_EXTRA _name : _type
# if __has_feature(generalized_swift_name)
#  define SWIFT_ENUM_NAMED(_type, _name, SWIFT_NAME, _extensibility) enum _name : _type _name SWIFT_COMPILE_NAME(SWIFT_NAME); enum SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_ENUM_ATTR(_extensibility) SWIFT_ENUM_EXTRA _name : _type
# else
#  define SWIFT_ENUM_NAMED(_type, _name, SWIFT_NAME, _extensibility) SWIFT_ENUM(_type, _name, _extensibility)
# endif
#endif
#if !defined(SWIFT_UNAVAILABLE)
# define SWIFT_UNAVAILABLE __attribute__((unavailable))
#endif
#if !defined(SWIFT_UNAVAILABLE_MSG)
# define SWIFT_UNAVAILABLE_MSG(msg) __attribute__((unavailable(msg)))
#endif
#if !defined(SWIFT_AVAILABILITY)
# define SWIFT_AVAILABILITY(plat, ...) __attribute__((availability(plat, __VA_ARGS__)))
#endif
#if !defined(SWIFT_WEAK_IMPORT)
# define SWIFT_WEAK_IMPORT __attribute__((weak_import))
#endif
#if !defined(SWIFT_DEPRECATED)
# define SWIFT_DEPRECATED __attribute__((deprecated))
#endif
#if !defined(SWIFT_DEPRECATED_MSG)
# define SWIFT_DEPRECATED_MSG(...) __attribute__((deprecated(__VA_ARGS__)))
#endif
#if !defined(SWIFT_DEPRECATED_OBJC)
# if __has_feature(attribute_diagnose_if_objc)
#  define SWIFT_DEPRECATED_OBJC(Msg) __attribute__((diagnose_if(1, Msg, "warning")))
# else
#  define SWIFT_DEPRECATED_OBJC(Msg) SWIFT_DEPRECATED_MSG(Msg)
# endif
#endif
#if defined(__OBJC__)
#if !defined(IBSegueAction)
# define IBSegueAction 
#endif
#endif
#if !defined(SWIFT_EXTERN)
# if defined(__cplusplus)
#  define SWIFT_EXTERN extern "C"
# else
#  define SWIFT_EXTERN extern
# endif
#endif
#if !defined(SWIFT_CALL)
# define SWIFT_CALL __attribute__((swiftcall))
#endif
#if !defined(SWIFT_INDIRECT_RESULT)
# define SWIFT_INDIRECT_RESULT __attribute__((swift_indirect_result))
#endif
#if !defined(SWIFT_CONTEXT)
# define SWIFT_CONTEXT __attribute__((swift_context))
#endif
#if !defined(SWIFT_ERROR_RESULT)
# define SWIFT_ERROR_RESULT __attribute__((swift_error_result))
#endif
#if defined(__cplusplus)
# define SWIFT_NOEXCEPT noexcept
#else
# define SWIFT_NOEXCEPT 
#endif
#if !defined(SWIFT_C_INLINE_THUNK)
# if __has_attribute(always_inline)
# if __has_attribute(nodebug)
#  define SWIFT_C_INLINE_THUNK inline __attribute__((always_inline)) __attribute__((nodebug))
# else
#  define SWIFT_C_INLINE_THUNK inline __attribute__((always_inline))
# endif
# else
#  define SWIFT_C_INLINE_THUNK inline
# endif
#endif
#if defined(_WIN32)
#if !defined(SWIFT_IMPORT_STDLIB_SYMBOL)
# define SWIFT_IMPORT_STDLIB_SYMBOL __declspec(dllimport)
#endif
#else
#if !defined(SWIFT_IMPORT_STDLIB_SYMBOL)
# define SWIFT_IMPORT_STDLIB_SYMBOL 
#endif
#endif
#if defined(__OBJC__)
#if __has_feature(objc_modules)
#if __has_warning("-Watimport-in-framework-header")
#pragma clang diagnostic ignored "-Watimport-in-framework-header"
#endif
@import CoreFoundation;
@import Foundation;
@import ObjectiveC;
@import UIKit;
#endif

#import <CleverAdsSolutions/CleverAdsSolutions.h>

#endif
#pragma clang diagnostic ignored "-Wproperty-attribute-mismatch"
#pragma clang diagnostic ignored "-Wduplicate-method-arg"
#if __has_warning("-Wpragma-clang-attribute")
# pragma clang diagnostic ignored "-Wpragma-clang-attribute"
#endif
#pragma clang diagnostic ignored "-Wunknown-pragmas"
#pragma clang diagnostic ignored "-Wnullability"
#pragma clang diagnostic ignored "-Wdollar-in-identifier-extension"
#pragma clang diagnostic ignored "-Wunsafe-buffer-usage"

#if __has_attribute(external_source_symbol)
# pragma push_macro("any")
# undef any
# pragma clang attribute push(__attribute__((external_source_symbol(language="Swift", defined_in="CleverAdsSolutions",generated_declaration))), apply_to=any(function,enum,objc_interface,objc_category,objc_protocol))
# pragma pop_macro("any")
#endif

#if defined(__OBJC__)
typedef SWIFT_ENUM_NAMED(NSInteger, CASNetworkId, "AdNetworkId", open) {
  CASNetworkIdGoogleAds = 0,
  CASNetworkIdLiftoffMonetize = 1,
  CASNetworkIdKidoz = 2,
  CASNetworkIdChartboost = 3,
  CASNetworkIdUnityAds = 4,
  CASNetworkIdAppLovin = 5,
  CASNetworkIdSuperAwesome = 6,
  CASNetworkIdStartIO = 7,
  CASNetworkIdAudienceNetwork = 9,
  CASNetworkIdInMobi = 10,
  CASNetworkIdDTExchange = 11,
  CASNetworkIdMyTarget = 12,
  CASNetworkIdCrosspromo = 13,
  CASNetworkIdIronSource = 14,
  CASNetworkIdYandexAds = 15,
  CASNetworkIdHyprMX = 16,
  CASNetworkIdSmaato = 18,
  CASNetworkIdBigo = 19,
  CASNetworkIdMadex = 21,
  CASNetworkIdMintegral = 23,
  CASNetworkIdPangle = 24,
  CASNetworkIdDSPExchange = 30,
  CASNetworkIdLastPageAd = 31,
};

enum CASType : NSInteger;
@class NSString;
enum CASPriceAccuracy : NSInteger;

SWIFT_PROTOCOL_NAMED("CASImpression")
@protocol CASStatusHandler <NSObject>
/// The Format Type of the impression
@property (nonatomic, readonly) enum CASType adType;
/// The mediated network’s name that purchased the impression.
/// All mediation network constants from <code>CASNetwork</code>.
@property (nonatomic, readonly, copy) NSString * _Nonnull network;
/// The Cost Per Mille estimated impressions of the ad in USD.
/// The value accuracy is returned in the <code>priceAccuracy</code> property.
@property (nonatomic, readonly) double cpm;
/// Accuracy of the cpm value. May return one of the following:
@property (nonatomic, readonly) enum CASPriceAccuracy priceAccuracy;
/// Version of the network SDK rendering the ad.
@property (nonatomic, readonly, copy) NSString * _Nonnull versionInfo;
/// The creative id tied to the ad, if available. May be nil.
/// You can report creative issues to our Ad review team using this id.
@property (nonatomic, readonly, copy) NSString * _Nullable creativeIdentifier;
/// The placement ID from the network that showed the ad
@property (nonatomic, readonly, copy) NSString * _Nonnull identifier;
/// The amount of impressions of all ad formats to the current user for all sessions.
@property (nonatomic, readonly) NSInteger impressionDepth;
/// The total revenue in USD from impressions of all ad formats to the current user for all sessions.
@property (nonatomic, readonly) double lifetimeRevenue;
/// Not used deprecated API
@property (nonatomic, readonly, copy) NSString * _Nonnull status;
/// Not used deprecated API
@property (nonatomic, readonly, copy) NSString * _Nonnull error;
/// Not used deprecated API
- (BOOL)isAdCached SWIFT_WARN_UNUSED_RESULT;
/// Not used deprecated API
- (void)toggleIgnoreMode;
@end


SWIFT_CLASS_NAMED("MediationUnit")
@interface CASMediationUnit : NSObject <CASStatusHandler>
@property (nonatomic, copy) NSString * _Nullable creativeIdentifier;
@property (nonatomic) double cpm;
@property (nonatomic, readonly, copy) NSString * _Nonnull network;
@property (nonatomic, readonly, copy) NSString * _Nonnull identifier;
@property (nonatomic, copy) NSString * _Nonnull error;
@property (nonatomic) enum CASPriceAccuracy priceAccuracy;
@property (nonatomic, readonly, copy) NSString * _Nonnull status;
@property (nonatomic, readonly) enum CASType adType;
@property (nonatomic, readonly, copy) NSString * _Nonnull versionInfo;
@property (nonatomic, readonly) NSInteger impressionDepth;
@property (nonatomic, readonly) double lifetimeRevenue;
- (BOOL)isAdCached SWIFT_WARN_UNUSED_RESULT;
- (void)toggleIgnoreMode;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end


SWIFT_CLASS_NAMED("BiddingUnit")
@interface CASBiddingUnit : CASMediationUnit
@property (nonatomic) double cpm;
@property (nonatomic) enum CASType adType;
- (BOOL)isAdCached SWIFT_WARN_UNUSED_RESULT;
- (void)toggleIgnoreMode;
@end

@class CASSettings;
@class CASTargetingOptions;
@class CASMediationManager;
@class CASManagerBuilder;
enum CASError : NSInteger;

SWIFT_CLASS_NAMED("CAS")
@interface CAS : NSObject
/// Get singleton instance to configure all mediation managers
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, strong) CASSettings * _Nonnull settings;)
+ (CASSettings * _Nonnull)settings SWIFT_WARN_UNUSED_RESULT;
/// You can now easily tailor the way you serve your ads to fit a specific audience!
/// You’ll need to inform our servers of the users details
/// so the SDK will know to serve ads according to the segment the user belongs to.
/// <em>Attention:</em> Must be set before initializing the SDK
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, strong) CASTargetingOptions * _Nonnull targetingOptions;)
+ (CASTargetingOptions * _Nonnull)targetingOptions SWIFT_WARN_UNUSED_RESULT;
/// Get last created <code>CASMediationManager</code> by <code>CAS.create()</code>
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, strong) CASMediationManager * _Nullable manager;)
+ (CASMediationManager * _Nullable)manager SWIFT_WARN_UNUSED_RESULT;
+ (void)setManager:(CASMediationManager * _Nullable)value;
/// Create <code>CASMediationManager</code> builder.
/// Don’t forget to call the <code>ManagerBuilder.create</code> method to create manager instance.
+ (CASManagerBuilder * _Nonnull)buildManager SWIFT_WARN_UNUSED_RESULT;
+ (NSString * _Nonnull)getSDKVersion SWIFT_WARN_UNUSED_RESULT;
/// Call Integration Helper and check current integration in console.
/// Log tag: [CASIntegrationHelper]
+ (void)validateIntegration;
+ (NSString * _Nonnull)getMessageOf:(enum CASError)error SWIFT_WARN_UNUSED_RESULT;
+ (enum CASError)getErrorFor:(NSString * _Nullable)message SWIFT_WARN_UNUSED_RESULT;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end

@class CASMediationAdapter;
@class CASConsentPlatform;

SWIFT_PROTOCOL_NAMED("CASAdapterFactory")
@protocol CASAdapterFactory <NSObject>
- (nonnull instancetype)init;
- (CASMediationAdapter * _Nonnull)create SWIFT_WARN_UNUSED_RESULT;
@optional
- (CASConsentPlatform * _Nonnull)createCMP SWIFT_WARN_UNUSED_RESULT;
@end

@protocol CASAnalyticsDelegate;

SWIFT_CLASS("_TtC18CleverAdsSolutions12CASAnalytics")
@interface CASAnalytics : NSObject
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, weak) id <CASAnalyticsDelegate> _Nullable delegate;)
+ (id <CASAnalyticsDelegate> _Nullable)delegate SWIFT_WARN_UNUSED_RESULT;
+ (void)setDelegate:(id <CASAnalyticsDelegate> _Nullable)value;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, copy) NSString * _Nonnull eventNameForCrossPromo;)
+ (NSString * _Nonnull)eventNameForCrossPromo SWIFT_WARN_UNUSED_RESULT;
+ (void)setEventNameForCrossPromo:(NSString * _Nonnull)value;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, copy) NSString * _Nonnull eventNameForImpressions;)
+ (NSString * _Nonnull)eventNameForImpressions SWIFT_WARN_UNUSED_RESULT;
+ (void)setEventNameForImpressions:(NSString * _Nonnull)value;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, copy) NSString * _Nonnull eventNameForErrors;)
+ (NSString * _Nonnull)eventNameForErrors SWIFT_WARN_UNUSED_RESULT;
+ (void)setEventNameForErrors:(NSString * _Nonnull)value;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, copy) NSString * _Nonnull eventNameForMediation;)
+ (NSString * _Nonnull)eventNameForMediation SWIFT_WARN_UNUSED_RESULT;
+ (void)setEventNameForMediation:(NSString * _Nonnull)value;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_PROTOCOL("_TtP18CleverAdsSolutions20CASAnalyticsDelegate_")
@protocol CASAnalyticsDelegate
- (void)analyticsEvent:(NSString * _Nonnull)eventName map:(NSDictionary<NSString *, id> * _Nonnull)map;
@end

@protocol CASCallback;
@class UIViewController;

SWIFT_CLASS_NAMED("CASAppOpen")
@interface CASAppOpen : NSObject
/// Returns the ad manager ID.
@property (nonatomic, readonly, copy) NSString * _Nonnull managerId;
/// Registers a weak delegate to be invoked when ads show and dismiss full screen content.
@property (nonatomic, weak) id <CASCallback> _Nullable contentCallback;
+ (CASAppOpen * _Nonnull)createWithManagerId:(NSString * _Nonnull)managerId SWIFT_WARN_UNUSED_RESULT;
+ (CASAppOpen * _Nonnull)createWithManager:(CASMediationManager * _Nonnull)manager SWIFT_WARN_UNUSED_RESULT;
/// Loads an AppOpenAd.
/// Note: You must keep a strong link throughout the ad’s lifecycle.
/// \param completionHandler An object that handles events for loading an app open ad
///
- (void)loadAdWithCompletionHandler:(void (^ _Nonnull)(CASAppOpen * _Nonnull, NSError * _Nullable))completionHandler;
/// Loads an AppOpenAd.
/// Note: You must keep a strong link throughout the ad’s lifecycle.
/// \param orientation The orientation that the ad will be presented in.
///
/// \param completionHandler An object that handles events for loading an app open ad
///
- (void)loadAdWithOrientation:(UIInterfaceOrientation)orientation completionHandler:(void (^ _Nonnull)(CASAppOpen * _Nonnull, NSError * _Nullable))completionHandler SWIFT_DEPRECATED_MSG("Loading app open ads now assumes the current orientation of the device, matching other full-screen formats.");
- (BOOL)isAdAvailable SWIFT_WARN_UNUSED_RESULT;
- (void)presentFromRootViewController:(UIViewController * _Nonnull)controller;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end


/// The CAS can execute callbacks on the UI or background thread.
SWIFT_PROTOCOL_NAMED("CASCallback")
@protocol CASCallback
@optional
/// Executed when the ad is displayed.
/// \param adStatus Information of displayed ad
///
- (void)willShownWithAd:(id <CASStatusHandler> _Nonnull)adStatus;
/// Executed when the ad is failed to display.
/// The Banner may automatically appear when the Ad is ready again.
/// This will trigger the <code>willShown(ad:)</code> callback again.
/// \param error Error message
///
- (void)didShowAdFailedWithError:(NSString * _Nonnull)error;
/// Executed when the user clicks on an Ad.
- (void)didClickedAd;
/// Executed when the Ad is completed.
/// Banner Ad does not use this callback.
- (void)didCompletedAd;
/// Executed when the ad is closed.
/// The Banner Ad cannot be displayed automatically after this callback for the current view.
/// If you decide to show the Banner Ad on this view then you need refresh view visibility.
- (void)didClosedAd;
@end


SWIFT_PROTOCOL("_TtP18CleverAdsSolutions20CASAppReturnDelegate_")
@protocol CASAppReturnDelegate <CASCallback>
- (UIViewController * _Nonnull)viewControllerForPresentingAppReturnAd SWIFT_WARN_UNUSED_RESULT;
@end

typedef SWIFT_ENUM_NAMED(NSInteger, CASAudience, "CASAudience", open) {
/// The user’s age has not been determined.
  CASAudienceUndefined = 0,
/// Audiences under the age of 13 who subject of COPPA.
/// When using this feature, a Tag For Users under the Age of Consent in Europe (TFUA) parameter
/// will be included in the ad request.
/// Also the state of GDPR and CCPA will be overridden automatically
/// to <code>CASConsentStatus.denied</code> and  <code>CASCCPAStatus.optOutSale</code>
  CASAudienceChildren = 1,
/// Audiences over the age of 13 NOT subject to the restrictions of child protection laws.
  CASAudienceNotChildren = 2,
};

@class CASBannerView;

/// The CAS can execute callbacks on the UI or background thread.
SWIFT_PROTOCOL_NAMED("CASBannerDelegate")
@protocol CASBannerDelegate
@optional
/// Invokes this callback when ad loaded and ready to present.
- (void)bannerAdViewDidLoad:(CASBannerView * _Nonnull)view;
/// Invokes this callback when an error occurred with the ad.
/// <ul>
///   <li>
///     To see a description of the error, see <code>AdError.message</code>.
///   </li>
/// </ul>
- (void)bannerAdView:(CASBannerView * _Nonnull)adView didFailWith:(enum CASError)error;
/// Invokes this callback when the new ad will presenting for user with info about the impression.
- (void)bannerAdView:(CASBannerView * _Nonnull)adView willPresent:(id <CASStatusHandler> _Nonnull)impression;
/// Invokes this callback when a user clicks the ad.
- (void)bannerAdViewDidRecordClick:(CASBannerView * _Nonnull)adView;
@end

@class NSCoder;

SWIFT_CLASS("_TtC18CleverAdsSolutions17CASBannerInternal")
@interface CASBannerInternal : UIView
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)coder SWIFT_UNAVAILABLE;
@property (nonatomic, getter=isHidden) BOOL hidden;
@property (nonatomic) CGFloat alpha;
@property (nonatomic, readonly) CGSize intrinsicContentSize;
- (void)didMoveToWindow;
- (void)didMoveToSuperview;
- (nonnull instancetype)initWithFrame:(CGRect)frame SWIFT_UNAVAILABLE;
@end

@class CASSize;

SWIFT_CLASS("_TtC18CleverAdsSolutions13CASBannerView")
@interface CASBannerView : CASBannerInternal
/// Initializes and returns a banner view with the specified ad size placed at its superview’s
/// origin.
- (nonnull instancetype)initWithAdSize:(CASSize * _Nonnull)adSize manager:(CASMediationManager * _Nullable)manager;
/// Initializes and returns a banner view with the specified ad size and origin relative to the
/// banner’s superview.
- (nonnull instancetype)initWithAdSize:(CASSize * _Nonnull)adSize origin:(CGPoint)origin manager:(CASMediationManager * _Nullable)manager OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)coder OBJC_DESIGNATED_INITIALIZER;
/// Active <code>CASMediationManager</code> to this banner view.
/// It can be automatically selected as the last active <code>CAS.manager</code> if it is NIL.
@property (nonatomic, strong) CASMediationManager * _Nullable manager;
/// Current banner ad size.
/// If autoload disabled (<code>isAutoloadEnabled = false</code>) then please call <code>loadNextAd</code> after banner size changed.
@property (nonatomic, strong) CASSize * _Nonnull adSize;
/// This view controller is used to present an overlay when the ad is clicked.
/// It should normally be set to the view controller that contains the <code>CASBannerView</code>
@property (nonatomic, weak) UIViewController * _Nullable rootViewController;
/// Through the use of <code>CASBannerDelegate</code>, you can listen for banner ads events.
@property (nonatomic, weak) id <CASBannerDelegate> _Nullable adDelegate;
/// Check ready banner ads
@property (nonatomic, readonly) BOOL isAdReady;
/// A Boolean value that determines whether autoloading of ads in the receiver is enabled.
/// If enabled, you do not need to call the <code>loadNextAd</code> method to load ads.
/// This value will override global state of <code>CASSettings.loadingMode</code>.
/// By default enabled if global state is NOT <code>CASSettings.setLoadingMode(CASLoadingManagerMode.Manual)</code>.
@property (nonatomic) BOOL isAutoloadEnabled;
/// Set the number of seconds an ad is displayed before a new ad is shown.
/// After the interval has passed, a new advertisement will be automatically loaded.
/// This value will override global <code>CASSettings.setBannerRefreshInterval</code>
@property (nonatomic) NSInteger refreshInterval;
/// Disable auto refresh ads.
- (void)disableAdRefresh;
/// Manual load Banner Ad or reload current loaded Ad for cancel impression.
/// If autoload disabled (<code>isAutoloadEnabled = false</code>) then you should use <code>loadNextAd</code> before present ad.
/// You can get a callback for the successful loading of an ad when set <code>adDelegate</code>
/// attention:
/// This functionality is available only after <code>CAS.create</code>
- (void)loadNextAd;
/// Destroy ad in the Banner View.
/// Call when banner ad is no longer needed.
- (void)destroy;
@end


SWIFT_CLASS_NAMED("CASBridgeToBUnit")
@interface CASBridgeToBUnit : CASBiddingUnit
- (BOOL)isAdCached SWIFT_WARN_UNUSED_RESULT;
@end

typedef SWIFT_ENUM_NAMED(NSInteger, CASCCPAStatus, "CASCCPAStatus", open) {
/// Mediation ads network behavior
  CASCCPAStatusUndefined = 0,
/// User does not consent to the sale of his or her personal information in compliance with CCPA.
  CASCCPAStatusOptOutSale = 1,
/// User consents to the sale of his or her personal information in compliance with CCPA.
  CASCCPAStatusOptInSale = 2,
};



SWIFT_CLASS_NAMED("CASChoicesView")
@interface CASChoicesView : UIView
@property (nonatomic, readonly) CGSize intrinsicContentSize;
- (void)layoutSubviews;
- (nonnull instancetype)initWithFrame:(CGRect)frame OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)coder OBJC_DESIGNATED_INITIALIZER;
@end

enum CASConsentFlowStatus : NSInteger;
enum CASUserDebugGeography : NSInteger;

/// Use this object for configure Consent flow dialogs for GDPR and Apple ATT request.
/// Create and attach the object to CAS initialization.
/// \code
/// CAS.buildManager()
///    .withConsentFlow(
///         CASConsentFlow()
///             .withPrivacyPolicy("https://url_to_privacy_policy")
///    )
///    .create()
///
/// \endcodeBy default, the consent flow will be shown to users who are protected by laws.
/// You can prevent us from showing the consent dialog to the user ussing followed lines:
/// \code
/// CAS.buildManager()
///     .withConsentFlow(
///         CASConsentFlow(isEnabled: false)
///     )
///     .create()
///
/// \endcode
SWIFT_CLASS_NAMED("CASConsentFlow")
@interface CASConsentFlow : NSObject
@property (nonatomic) BOOL requestGDPR;
@property (nonatomic) BOOL requestATT SWIFT_DEPRECATED_MSG("The GDPR and ATT request does not support partial activation. Use requestGDPR instead.");
@property (nonatomic) BOOL forceTesting;
@property (nonatomic, copy) NSString * _Nullable privacyPolicyUrl;
@property (nonatomic, copy) void (^ _Nullable completionHandler)(enum CASConsentFlowStatus);
@property (nonatomic, strong) UIViewController * _Nullable viewControllerToPresent;
@property (nonatomic) enum CASUserDebugGeography debugGeography;
/// Create Consent flow configuration
/// \param isEnabled If enabled then the consent flow will be shown to users who are protected by laws.
///
- (nonnull instancetype)initWithEnabled:(BOOL)isEnabled OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
/// Override the UI context in which the form should run.
/// If you do not define a context, it will be determined automatically.
/// The form can open on each new UIViewController until the user closes it.
- (CASConsentFlow * _Nonnull)withViewControllerToPresent:(UIViewController * _Nullable)controller;
/// Shows the consent form only if it is required and the user has not responded previously.
/// If the consent status is required, the SDK loads a form and immediately presents it.
- (void)presentIfRequired;
/// Force shows the form to modify user  consent at any time.
/// When a user interacts with your UI element, call function to show the form
/// so the user can update their privacy options at any time.
- (void)present;
@end

typedef SWIFT_ENUM_NAMED(NSInteger, CASUserDebugGeography, "DebugGeography", open) {
/// Debug geography disabled.
  CASUserDebugGeographyDisabled = 0,
/// Geography appears as in EEA.
  CASUserDebugGeographyEEA = 1,
/// Geography appears as not in EEA.
  CASUserDebugGeographyNotEEA = 2,
};

typedef SWIFT_ENUM_NAMED(NSInteger, CASConsentFlowStatus, "CASConsentFlowStatus", open) {
/// User consent obtained. Personalized vs non-personalized undefined.
  CASConsentFlowStatusObtained = 3,
/// User consent not required.
  CASConsentFlowStatusNotRequired = 4,
/// User consent unavailable.
  CASConsentFlowStatusUnavailable = 5,
/// There was an internal error.
  CASConsentFlowStatusInternalError = 10,
/// There was an error loading data from the network.
  CASConsentFlowStatusNetworkError = 11,
/// There was an error with the UI context is passed in.
  CASConsentFlowStatusViewControllerInvalid = 12,
/// There was an error with another form is still being displayed.
  CASConsentFlowStatusFlowStillPresenting = 13,
};


SWIFT_CLASS("_TtC18CleverAdsSolutions18CASConsentPlatform")
@interface CASConsentPlatform : NSObject
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end

typedef SWIFT_ENUM_NAMED(NSInteger, CASConsentStatus, "CASConsentStatus", open) {
/// Mediation ads network behavior
  CASConsentStatusUndefined = 0,
/// User consents to behavioral targeting in compliance with GDPR.
  CASConsentStatusAccepted = 1,
/// User does not consent to behavioral targeting in compliance with GDPR.
  CASConsentStatusDenied = 2,
};

typedef SWIFT_ENUM_NAMED(NSInteger, CASError, "CASError", open) {
  CASErrorInternalError = 0,
/// Loading ads cannot be successful without an internet connection.
  CASErrorNoConnection = 2,
/// This means we are not able to serve ads to this person.
/// Note that if you can see ads while you are testing with enabled <code>CAS.create(demoAdMode: true)</code>,
/// your implementation works correctly and people will be able to see ads in your app once it’s live.
  CASErrorNoFill = 3,
/// A configuration error has been detected in one of the mediation ad networks.
/// Please report error message to your manager support.
  CASErrorConfigurationError = 6,
/// Ad are not ready to show.
/// You need to call Load ads or use one of the automatic cache mode.
/// If you are already using automatic cache mode then just wait a little longer.
/// You can always check if ad is ready to show using methods:
/// \code
/// CASMediationManager.isInterstitialReady
/// CASMediationManager.isRewardedReady
/// CASBannerView.isAdReady
///
/// \endcode
  CASErrorNotReady = 1001,
/// The manager you want to use is not active at the moment.
/// To change the state of the manager, use method:
/// \code
/// CASMediationManager.setEnabled
///
/// \endcode
  CASErrorManagerIsDisabled = 1002,
/// Ad creative has reached its daily cap for user.
  CASErrorReachedCap = 1004,
/// There is not enough space in the current view for the selected <code>CASSize</code>.
/// Please make sure that the size of the banner container has enough free space.
/// You can choose a smaller size if necessary using  property:
/// \code
/// CASBannerView.adSize
///
/// \endcode
  CASErrorNotEnoughSpace = 1005,
/// The interval between impressions of Interstitial Ad has not yet passed.
/// To change the interval, use  method:
/// \code
/// CASSettings.setInterstitial(interval:)
///
/// \endcode
  CASErrorIntervalNotYetPassed = 2001,
/// You can not show ads because another fullscreen ad is being displayed at the moment.
/// Please check your ad call logic to eliminate duplicate impressions.
  CASErrorAlreadyDisplayed = 2002,
/// Ads cannot be shown as the application is currently not visible to the user.
  CASErrorAppIsPaused = 2003,
/// All the rootViewController parameters in Ad APIs must be provided to process ad redirects.
/// In the SDK, all redirects use the present method.
/// Therefore, make sure that the passed rootViewController parameters are not null and do not have other present controllers.
/// Otherwise the present will fail because presentedViewController already exists.
  CASErrorInvalidUIViewController = 3001,
};
static NSString * _Nonnull const CASErrorDomain = @"CleverAdsSolutions.CASError";



SWIFT_CLASS_NAMED("CASInitialConfig")
@interface CASInitialConfig : NSObject
/// Get the CAS manager initialization error message or NULL if initialization is successful.
/// Check errors constants from CASInitializationError class.
@property (nonatomic, readonly, copy) NSString * _Nullable error;
/// Get the initialized CAS manager.
@property (nonatomic, readonly, strong) CASMediationManager * _Nonnull manager;
/// Get the user’s ISO-2 country code.
@property (nonatomic, readonly, copy) NSString * _Nullable countryCode;
/// The consent must be requested from the user.
@property (nonatomic, readonly) BOOL isConsentRequired;
/// Returns true if the user authorizes access to app-related data for tracking the user or the device.
/// seealso:
/// <a href="https://developer.apple.com/documentation/apptrackingtransparency/attrackingmanager">App Tracking Transparency</a>
@property (nonatomic, readonly) BOOL isATTrackingAuthorized;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end


SWIFT_CLASS_NAMED("CASLastPageAdContent")
@interface CASLastPageAdContent : NSObject
/// Create Ad content to use in Last Page
/// The latest free ad page for your own promotion
/// This ad page will be displayed when there is no paid ad to show or internet availability.
/// Apply this content to <code>MediationManager.lastPageAdContent</code>
/// \param headline Enter the message that you want users to see.
///
/// \param adText Enter a description for the app being promoted. Optional property.
///
/// \param destinationURL Enter the URL that CAS will direct users to when they click the ad. This URL is not visible in the ad.
///
/// \param imageURL Enter the direct URL of the image to be used as the ad file. Optional property.
///
/// \param iconURL Enter the direct URL of the icon or logo (Small square picture). Optional property.
///
- (nonnull instancetype)initWithHeadline:(NSString * _Nonnull)headline adText:(NSString * _Nonnull)adText destinationURL:(NSString * _Nonnull)destinationURL imageURL:(NSString * _Nonnull)imageURL iconURL:(NSString * _Nonnull)iconURL OBJC_DESIGNATED_INITIALIZER;
+ (CASLastPageAdContent * _Nullable)createFrom:(NSString * _Nullable)json SWIFT_WARN_UNUSED_RESULT;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end


SWIFT_PROTOCOL_NAMED("CASLoadDelegate")
@protocol CASLoadDelegate
/// Executed when the ad loaded and ready to present.
/// attention:
/// Can be called from ANY Thread and not UI Thread safe.
- (void)onAdLoaded:(enum CASType)adType;
/// Executed when the ad failed to load.
/// attention:
/// Can be called from ANY Thread and not UI Thread safe.
- (void)onAdFailedToLoad:(enum CASType)adType withError:(NSString * _Nullable)error;
@end

typedef SWIFT_ENUM_NAMED(NSInteger, CASLoadingManagerMode, "CASLoadingManagerMode", open) {
/// Automatic control loading mediation ads.
/// Provides frequent polling of mediation networks for advertising content.
/// May increase coverage with more expensive ads.
/// But this will run more background processes that slow down the application.
  CASLoadingManagerModeFastestRequests = 0,
/// Automatic control loading mediation ads.
/// Provides frequent polling of mediation networks for advertising content.
/// May increase coverage with more expensive ads.
/// But this will run more background processes that slow down the application.
  CASLoadingManagerModeFastRequests = 1,
/// Automatic control loading mediation ads.
/// Provides balanced polling rate of mediation networks for advertising content.
/// Doesn’t significantly affect application performance.
  CASLoadingManagerModeOptimal = 2,
/// Automatic control loading mediation ads.
/// Provides slow polling of mediation networks for advertising content.
/// This helps to reduce the impact of background processes on the application.
/// At the same time, do not lose much of the relevance of the high cost of advertising content.
/// Reduces memory reservations for advertising content.
  CASLoadingManagerModeHighePerformance = 3,
/// Automatic control loading mediation ads.
/// Provides slow polling of mediation networks for advertising content.
/// This helps to reduce the impact of background processes on the application.
/// At the same time, do not lose much of the relevance of the high cost of advertising content.
/// Reduces memory reservations for advertising content.
  CASLoadingManagerModeHighestPerformance = 4,
/// Manual control loading mediation ads.
/// Provides minimal impact on application performance.
/// But it requires manual preparation of advertising content for display.
/// Use ad loading methods before trying to show:
/// <code>CASMediationManager.loadInterstitial()</code>, <code>CASMediationManager.loadRewardedVideo()</code>, <code>CASBannerView.loadNextAd()</code>
/// Reduces memory reservations for advertising content.
  CASLoadingManagerModeManual = 5,
};


SWIFT_CLASS_NAMED("CASManagerBuilder")
@interface CASManagerBuilder : NSObject
/// Set handler to receive a callback after all CAS initialization processes have completed.
- (CASManagerBuilder * _Nonnull)withCompletionHandler:(void (^ _Nonnull)(CASInitialConfig * _Nonnull))handler;
/// Enable test ad mode that will always request test ads.
/// <em>Attention</em> Don’t forget to set it to False after the tests are completed.
- (CASManagerBuilder * _Nonnull)withTestAdMode:(BOOL)test;
/// Using <code>CASTypeFlags</code> in current session.
/// By default: All Ad types are used.
/// Set <code>CASTypeFlags.none</code> to disable all ad types requests.
- (CASManagerBuilder * _Nonnull)withAdFlags:(CASTypeFlags)adTypes;
/// The userID is a unique identifier supplied by your application and must be static for each user across sessions.
/// Your userID should not contain any personally identifiable information such as an email address, screen name.
- (CASManagerBuilder * _Nonnull)withUserID:(NSString * _Nonnull)userID;
/// Create and attach the Conset flow configuration for initialization.
/// \code
/// .withConsentFlow(
///      CASConsentFlow()
///          .withPrivacyPolicy("https://url_to_privacy_policy")
/// )
///
/// \endcodeBy default, the consent flow will be shown to users who are protected by laws.
/// You can prevent us from showing the consent dialog to the user ussing followed lines:
/// \code
/// .withConsentFlow(CASConsentFlow(isEnabled: false))
///
/// \endcode
- (CASManagerBuilder * _Nonnull)withConsentFlow:(CASConsentFlow * _Nonnull)flow;
/// Additional mediation settings.
- (CASManagerBuilder * _Nonnull)withMediationExtras:(NSString * _Nonnull)value forKey:(NSString * _Nonnull)key;
/// Information about the platform on which the application runs.
/// Platforms such as Unity, Cordova, Flutter…
/// If your app only uses native android then don’t call this function.
- (CASManagerBuilder * _Nonnull)withFramework:(NSString * _Nonnull)name version:(NSString * _Nonnull)version;
/// Create new or get valid <code>CASMediationManager</code>.
/// Can be called for different identifiers to create different managers.
/// An CAS ID is a unique ID number assigned to each of your ad placements when they’re created in CAS.
/// <ul>
///   <li>
///     The CAS ID is added to your app’s code and used to identify ad requests.
///     Often the CAS ID is the same as the Apple  ID.
///   </li>
///   <li>
///     If you haven’t created an CAS account and registered an app yet, now’s a great time to do so at <a href="https://cleveradssolutions.com">cleveradssolutions.com</a>.
///   </li>
///   <li>
///     In a real app, it is important that you use your actual CAS ID.
///   </li>
/// </ul>
- (CASMediationManager * _Nonnull)createWithCasId:(NSString * _Nonnull)identifier SWIFT_WARN_UNUSED_RESULT;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS_NAMED("CASMediaView")
@interface CASMediaView : UIView
@property (nonatomic, readonly) CGSize intrinsicContentSize;
@property (nonatomic) UIViewContentMode contentMode;
- (nonnull instancetype)initWithFrame:(CGRect)frame OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)coder OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS_NAMED("CASMediationManager")
@interface CASMediationManager : NSObject
/// Weak event on <code>CASType</code> load response.
@property (nonatomic, weak) id <CASLoadDelegate> _Nullable adLoadDelegate;
@property (nonatomic, readonly, copy) NSString * _Nonnull managerID;
@property (nonatomic, readonly) BOOL isDemoAdMode;
/// The latest free ad page to your own promotion.
/// This ad page will be displayed when there is no paid ad to show or internet availability.
/// By default, this page will not be displayed while the ad content is NIL.
/// <code>CASLastPageAdContent.destinationURL</code> should always have a non-empty URL.
/// attention:
/// Impressions and clicks of this ad page will not be billed.
@property (nonatomic, strong) CASLastPageAdContent * _Nullable lastPageAdContent;
/// Check is visible <code>CASType.interstitial</code>or <code>CASType.Rewarded</code> right now.
@property (nonatomic, readonly) BOOL isFullscreenAdVisible;
/// Manual load Interstitial Ad.
/// Please call load before each show ad.
/// You can get a callback for the successful loading of an ad when set <code>adLoadDelegate</code>
/// attention:
/// You should only use this method <code>if CASSettings.getLoadingMode() == CASLoadingManagerMode.manual</code> is active.
- (void)loadInterstitial;
/// Check if Interstitial ad is ready to be shown.
@property (nonatomic, readonly) BOOL isInterstitialReady;
/// Shows the Interstitial ad if available.
/// \param controller The controller from which the Interstitial ad should be shown.
///
/// \param callback The callback for Interstitial ad events.
///
- (void)presentInterstitialFromRootViewController:(UIViewController * _Nonnull)controller callback:(id <CASCallback> _Nullable)callback;
/// Manual load Rewarded Video Ad.
/// Please call load before each show ad.
/// You can get a callback for the successful loading of an ad when set <code>adLoadDelegate</code>
/// attention:
/// You should only use this method <code>if CASSettings.getLoadingMode() == CASLoadingManagerMode.manual</code> is active.
- (void)loadRewardedAd;
/// Check if Rewarded ad is ready to be shown.
@property (nonatomic, readonly) BOOL isRewardedAdReady;
/// Shows the Rewarded video ad if available.
/// \param controller The controller from which the Interstitial ad should be shown.
///
/// \param callback The callback for Interstitial ad events.
///
- (void)presentRewardedAdFromRootViewController:(UIViewController * _Nonnull)controller callback:(id <CASCallback> _Nullable)callback;
/// Ad [type] is processing.
- (BOOL)isEnabledWithType:(enum CASType)type SWIFT_WARN_UNUSED_RESULT;
/// Set [enabled] ad [type] to processing.
/// The state will not be saved between sessions.
- (void)setEnabled:(BOOL)enabled type:(enum CASType)type;
/// The Return Ad which is displayed once the user returns to your application after a certain period of time.
/// To minimize the intrusiveness, short time periods are ignored.
/// Return ads are disabled by default.
- (void)enableAppReturnAdsWith:(id <CASAppReturnDelegate> _Nonnull)delegate;
/// Disables App Return Ads
- (void)disableAppReturnAds;
/// Calling this method will indicate to skip one next ad impression when returning to the app.
/// You can call this method when you intentionally redirect the user to another application (for example App Store)
/// and do not want them to see ads when they return to your application.
- (void)skipNextAppReturnAds;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end


@class UILabel;
@class UIButton;
@class UIImageView;
@class CASNativeAdContent;

SWIFT_CLASS_NAMED("CASNativeView")
@interface CASNativeView : UIView
@property (nonatomic, weak) IBOutlet UIView * _Nullable mainView;
@property (nonatomic, weak) IBOutlet CASMediaView * _Nullable mediaView;
@property (nonatomic, weak) IBOutlet CASChoicesView * _Nullable adChoicesView;
@property (nonatomic, weak) IBOutlet UILabel * _Nullable headlineView;
@property (nonatomic, weak) IBOutlet UIButton * _Nullable callToActionView;
@property (nonatomic, weak) IBOutlet UIImageView * _Nullable iconView;
@property (nonatomic, weak) IBOutlet UILabel * _Nullable bodyView;
@property (nonatomic, weak) IBOutlet UILabel * _Nullable priceView;
@property (nonatomic, weak) IBOutlet UILabel * _Nullable advertiserView;
@property (nonatomic, weak) IBOutlet UILabel * _Nullable storeView;
@property (nonatomic, weak) IBOutlet UIView * _Nullable starRatingView;
@property (nonatomic, weak) IBOutlet UILabel * _Nullable reviewCountView;
@property (nonatomic, weak) IBOutlet UILabel * _Nullable adLabelView;
@property (nonatomic, readonly, copy) NSArray<UIView *> * _Nonnull clickableViews;
- (BOOL)setNativeAd:(CASNativeAdContent * _Nullable)ad error:(NSError * _Nullable * _Nullable)error;
- (nonnull instancetype)initWithFrame:(CGRect)frame OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)coder OBJC_DESIGNATED_INITIALIZER;
@end



SWIFT_CLASS_NAMED("CASNetwork")
@interface CASNetwork : NSObject
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, copy) NSString * _Nonnull casExchange;)
+ (NSString * _Nonnull)casExchange SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, copy) NSString * _Nonnull dspExchange;)
+ (NSString * _Nonnull)dspExchange SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, copy) NSString * _Nonnull crossPromo;)
+ (NSString * _Nonnull)crossPromo SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, copy) NSString * _Nonnull googleAds;)
+ (NSString * _Nonnull)googleAds SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, copy) NSString * _Nonnull vungle;)
+ (NSString * _Nonnull)vungle SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, copy) NSString * _Nonnull kidoz;)
+ (NSString * _Nonnull)kidoz SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, copy) NSString * _Nonnull chartboost;)
+ (NSString * _Nonnull)chartboost SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, copy) NSString * _Nonnull unityAds;)
+ (NSString * _Nonnull)unityAds SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, copy) NSString * _Nonnull appLovin;)
+ (NSString * _Nonnull)appLovin SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, copy) NSString * _Nonnull superAwesome;)
+ (NSString * _Nonnull)superAwesome SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, copy) NSString * _Nonnull meta;)
+ (NSString * _Nonnull)meta SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, copy) NSString * _Nonnull inMobi;)
+ (NSString * _Nonnull)inMobi SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, copy) NSString * _Nonnull ironSource;)
+ (NSString * _Nonnull)ironSource SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, copy) NSString * _Nonnull yandexAds;)
+ (NSString * _Nonnull)yandexAds SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, copy) NSString * _Nonnull mintegral;)
+ (NSString * _Nonnull)mintegral SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, copy) NSString * _Nonnull pangle;)
+ (NSString * _Nonnull)pangle SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, copy) NSString * _Nonnull dtExchange;)
+ (NSString * _Nonnull)dtExchange SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, copy) NSString * _Nonnull bigo;)
+ (NSString * _Nonnull)bigo SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, copy) NSString * _Nonnull hyprMX;)
+ (NSString * _Nonnull)hyprMX SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, copy) NSString * _Nonnull smaato;)
+ (NSString * _Nonnull)smaato SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, copy) NSString * _Nonnull startio;)
+ (NSString * _Nonnull)startio SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, copy) NSString * _Nonnull loopMe;)
+ (NSString * _Nonnull)loopMe SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, copy) NSString * _Nonnull madex;)
+ (NSString * _Nonnull)madex SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, copy) NSString * _Nonnull ogury;)
+ (NSString * _Nonnull)ogury SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, copy) NSString * _Nonnull lastPageAd;)
+ (NSString * _Nonnull)lastPageAd SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, copy) NSString * _Nonnull adMob;)
+ (NSString * _Nonnull)adMob SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, copy) NSString * _Nonnull facebookAN;)
+ (NSString * _Nonnull)facebookAN SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, copy) NSString * _Nonnull fyber;)
+ (NSString * _Nonnull)fyber SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, copy) NSString * _Nonnull digitalTurbine;)
+ (NSString * _Nonnull)digitalTurbine SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, copy) NSString * _Nonnull myTarget SWIFT_DEPRECATED_MSG("No longer supported");)
+ (NSString * _Nonnull)myTarget SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, copy) NSString * _Nonnull bidMachine SWIFT_DEPRECATED_MSG("No longer supported");)
+ (NSString * _Nonnull)bidMachine SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, copy) NSString * _Nonnull adColony SWIFT_DEPRECATED_MSG("No longer supported");)
+ (NSString * _Nonnull)adColony SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, copy) NSString * _Nonnull tapjoy SWIFT_DEPRECATED_MSG("No longer supported");)
+ (NSString * _Nonnull)tapjoy SWIFT_WARN_UNUSED_RESULT;
/// Meta Audience Network  Advertising Tracking Enabled
/// Set the <code>FBAdSettings.setAdvertiserTrackingEnabled</code> flag.
/// The setAdvertiserTrackingEnabled “1” flag allows you to inform Audience Network whether to use the data to deliver personalized ads in line with your own legal obligations,
/// platform terms, and commitments you’ve made to your users.
/// If the flag is set to “0” we will not be able to deliver personalized ads.
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, copy) NSString * _Nonnull facebookAdvertiserTracking;)
+ (NSString * _Nonnull)facebookAdvertiserTracking SWIFT_WARN_UNUSED_RESULT;
/// Meta Audience Network Data Processing Options for US Users
/// Limited Data Use is a data processing option that gives you more control over how your data
/// is used in Meta’s systems and better supports your compliance efforts with various US state
/// privacy regulations. To utilize this feature, you must proactively enable Limited Data Use.
/// Set the <code>FBAdSettings.setDataProcessingOptions</code> flag values:
/// <ul>
///   <li>
///     “” (empty string)  - To explicitly not enable Limited Data Use (LDU) mode
///   </li>
///   <li>
///     “LDU”  - To enable LDU mode using geolocation
///   </li>
/// </ul>
/// Visit Meta’s developer documentation for details:
/// https://developers.facebook.com/docs/marketing-apis/data-processing-options
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, copy) NSString * _Nonnull facebookDataProcessing;)
+ (NSString * _Nonnull)facebookDataProcessing SWIFT_WARN_UNUSED_RESULT;
/// Sets the publish IDFV flag
/// This value is persistent and so may be set once.
/// Default value is “1”.
/// if “0” no publish the IDFV value.
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, copy) NSString * _Nonnull vunglePublishIDFV;)
+ (NSString * _Nonnull)vunglePublishIDFV SWIFT_WARN_UNUSED_RESULT;
+ (NSString * _Nonnull)getDisplayName:(NSString * _Nonnull)net SWIFT_WARN_UNUSED_RESULT;
+ (NSString * _Nonnull)getActiveNetworkPattern SWIFT_WARN_UNUSED_RESULT;
+ (NSArray<NSString *> * _Nonnull)getActiveNetworks SWIFT_WARN_UNUSED_RESULT;
+ (BOOL)isActiveNetwork:(NSString * _Nonnull)network SWIFT_WARN_UNUSED_RESULT;
+ (NSArray<NSString *> * _Nonnull)values SWIFT_WARN_UNUSED_RESULT;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_PROTOCOL_NAMED("CASPaidCallback")
@protocol CASPaidCallback <CASCallback>
- (void)didPayRevenueFor:(id <CASStatusHandler> _Nonnull)ad;
@end

typedef SWIFT_ENUM_NAMED(NSInteger, CASPriceAccuracy, "CASPriceAccuracy", open) {
/// eCPM floor, also known as minimum eCPMs
  CASPriceAccuracyFloor = 0,
/// eCPM is the exact and committed value per 1000 impressions.
  CASPriceAccuracyBid = 1,
/// When the demand source does not agree to disclose the payout of every impression - in such cases the cpm is ‘0’
  CASPriceAccuracyUndisclosed = 2,
};


SWIFT_CLASS_NAMED("CASSettings")
@interface CASSettings : NSObject
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
/// Ad filters by Audience
/// Default: undefined
@property (nonatomic) enum CASAudience taggedAudience;
/// GDPR user Consent to use personal data in Ads requests.
/// Default CASConsentStatus undefined
@property (nonatomic) enum CASConsentStatus userConsent;
/// Parses the <code>UserDefaults</code> string with key <code>IABTCF_VendorConsents</code>
/// to determine the consent status of the IAB vendor with the provided ID.
/// \param vendorId Vendor ID as defined in the Global Vendor List.
///
///
/// returns:
/// <code>accepted</code> if the advertising entity has consent, <code>denied</code> if not, or <code>undefined</code> if VendorConsents is not available on disk.
/// @see <a href="https://iabeurope.eu/vendor-list-tcf/">TCF Vendor List</a>
- (enum CASConsentStatus)getVendorConsentWithVendorId:(NSInteger)vendorId SWIFT_WARN_UNUSED_RESULT;
/// Parses the <code>UserDefaults</code> string with key <code>IABTCF_AddtlConsent</code>
/// to determine the consent status of the advertising entity with the provided Ad Technology Provider (ATP) ID.
/// seealso:
/// <a href="https://support.google.com/admanager/answer/9681920">Google’s Additional Consent Mode technical specification</a>
/// seealso:
/// <a href="https://storage.googleapis.com/tcfac/additional-consent-providers.csv">List of Google ATPs and their IDs</a>
/// \param providerId ATP ID of the advertising entity (e.g. 89 for Meta Audience Network).
///
///
/// returns:
/// <code>accepted</code> if the advertising entity has consent, <code>denied</code> if not, or <code>undefined</code> if AddtlConsent is not available on disk.
- (enum CASConsentStatus)getAdditionalConsentWithProviderId:(NSInteger)providerId SWIFT_WARN_UNUSED_RESULT;
/// Whether or not user has opted out of the sale of their personal information.
/// Default CASCCPAStatus undefined
@property (nonatomic) enum CASCCPAStatus userCCPAStatus;
/// The SDK automatically collects location data if the user allowed the app to track the location.
- (BOOL)isTrackLocationEnabled SWIFT_WARN_UNUSED_RESULT SWIFT_DEPRECATED_MSG("Use CAS.targetingOptions.locationCollectionEnabled instead.");
/// The SDK automatically collects location data if the user allowed the app to track the location.
/// Disabled by default.
- (void)setTrackLocationWithEnabled:(BOOL)enabled SWIFT_DEPRECATED_MSG("Use CAS.targetingOptions.locationCollectionEnabled instead.");
/// Defines the time interval, in seconds, starting from the moment of the initial app installation,
/// during which users can use the application without ads being displayed while still retaining
/// access to the Rewarded Ads format.
/// Within this interval, users enjoy privileged access to the application’s features without intrusive advertisements.
/// <ul>
///   <li>
///     Default: 0 seconds
///   </li>
///   <li>
///     Units: Seconds
///   </li>
/// </ul>
@property (nonatomic) uint64_t trialAdFreeInterval;
/// Set the number of seconds an ad is displayed before a new ad is shown.
/// After the interval has passed, a new advertisement will be automatically loaded.
/// <code>CASBannerView.refreshInterval</code> will override this value for a specific view.
/// <ul>
///   <li>
///     Default: 30 seconds.
///   </li>
///   <li>
///     Units: Seconds
///   </li>
/// </ul>
@property (nonatomic) NSInteger bannerRefreshInterval;
/// The interval between impressions Interstitial Ad in seconds.
/// <ul>
///   <li>
///     Default: 0 seconds.
///   </li>
///   <li>
///     Units: Seconds
///   </li>
/// </ul>
/// Use <code>restartInterstitialInterval()</code> for restart interval until next Interstitial ad display.
@property (nonatomic) NSInteger interstitialInterval;
/// In Develop
@property (nonatomic) BOOL audioSessionIsApplicationManaged;
/// Restart interval until next Interstitial ad display.
/// By default, the interval before first Interstitial Ad impression is ignored.
/// You can use this method to delay displaying ad.
- (void)restartInterstitialInterval;
/// Indicates if the application’s audio is muted. Affects initial mute state for
/// all ads. Use this method only if your application has its own volume controls
/// (e.g., custom music or sound effect muting).
/// Disabled by default.
@property (nonatomic) BOOL mutedAdSounds;
/// The enabled Debug Mode will display a lot of useful information for debugging about the states of the sdk with tag CAS.
/// Disabling Debug Mode may improve application performance.
/// Disabled by default.
@property (nonatomic) BOOL debugMode;
/// Identifiers corresponding to test devices which will always request test ads.
/// List of test devices should be defined before first MediationManager initialized.
/// <ol>
///   <li>
///     Run an app configured with the CAS SDK.
///   </li>
///   <li>
///     Check the console or logcat output for a message that looks like this:
///     “To get test ads on this device, set … “
///   </li>
///   <li>
///     Copy your alphanumeric test device ID to your clipboard.
///   </li>
///   <li>
///     Modify your code to set the test device ID before CAS manager initialize.
///   </li>
///   <li>
///     Re-run your app.
///   </li>
///   <li>
///     Well done, ads on this device are safe to click. Requests, impressions, and clicks on ads in test mode will not show up in your account’s reports.
///   </li>
/// </ol>
- (void)setTestDeviceWithIds:(NSArray<NSString *> * _Nonnull)ids;
/// This option will compare ad cost and serve regular interstitial ads
/// when rewarded video ads are expected to generate less revenue.
/// Enabled by default.
/// attention:
/// Interstitial Ads does not require to watch the video to the end,
/// but the <code>CASCallback.didCompletedAd</code> callback will be triggered in any case.
- (void)setInterstitialAdsWhenVideoCostAreLowerWithAllow:(BOOL)allow;
/// This option will compare ad cost and serve regular interstitial ads
/// when rewarded video ads are expected to generate less revenue.
/// Enabled by default.
/// attention:
/// Interstitial Ads does not require to watch the video to the end,
/// but the <code>CASCallback.didCompletedAd</code> callback will be triggered in any case.
- (BOOL)isInterstitialAdsWhenVideoCostAreLowerAllowed SWIFT_WARN_UNUSED_RESULT;
/// Mediation loading manager mode.
/// Default: <code>CASLoadingManagerMode.optimal</code>
- (enum CASLoadingManagerMode)getLoadingMode SWIFT_WARN_UNUSED_RESULT;
/// Mediation loading manager mode.
/// Default: <code>CASLoadingManagerMode.optimal</code>
- (void)setLoadingWithMode:(enum CASLoadingManagerMode)mode;
@end



@interface CASSettings (SWIFT_EXTENSION(CleverAdsSolutions))
- (NSInteger)getBannerRefreshInterval SWIFT_WARN_UNUSED_RESULT SWIFT_DEPRECATED_MSG("Use bannerRefreshInterval property instead");
- (void)setBannerRefreshWithInterval:(NSInteger)interval SWIFT_DEPRECATED_MSG("Use bannerRefreshInterval property instead");
- (NSInteger)getInterstitialInterval SWIFT_WARN_UNUSED_RESULT SWIFT_DEPRECATED_MSG("Use interstitialInterval property instead");
- (void)setInterstitialWithInterval:(NSInteger)interval SWIFT_DEPRECATED_MSG("Use interstitialInterval property instead");
- (BOOL)isDebugMode SWIFT_WARN_UNUSED_RESULT;
- (BOOL)isMutedAdSounds SWIFT_WARN_UNUSED_RESULT;
- (void)setMuteAdSoundsTo:(BOOL)muted;
- (enum CASConsentStatus)getUserConsent SWIFT_WARN_UNUSED_RESULT SWIFT_DEPRECATED_MSG("Use userConsent property instead");
- (void)updateUserWithConsent:(enum CASConsentStatus)consent SWIFT_DEPRECATED_MSG("Use userConsent property instead");
- (enum CASCCPAStatus)getCCPAStatus SWIFT_WARN_UNUSED_RESULT SWIFT_DEPRECATED_MSG("Use userCCPAStatus property instead");
- (void)updateCCPAWithStatus:(enum CASCCPAStatus)status SWIFT_DEPRECATED_MSG("Use userCCPAStatus property instead");
- (enum CASAudience)getTaggedAudience SWIFT_WARN_UNUSED_RESULT SWIFT_DEPRECATED_MSG("Use taggedAudience property instead");
- (void)setTaggedWithAudience:(enum CASAudience)audience SWIFT_DEPRECATED_MSG("Use taggedAudience property instead");
- (BOOL)isAnalyticsCollectionEnabled SWIFT_WARN_UNUSED_RESULT SWIFT_DEPRECATED_MSG("No longer in use");
- (void)setAnalyticsCollectionWithEnabled:(BOOL)enabled SWIFT_DEPRECATED_MSG("No longer in use");
@end

@class UIWindow;

SWIFT_CLASS_NAMED("CASSize")
@interface CASSize : NSObject
@property (nonatomic, readonly) CGFloat width;
@property (nonatomic, readonly) CGFloat height;
/// Standard banner size 320dp width and 50dp height
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, strong) CASSize * _Nonnull banner;)
+ (CASSize * _Nonnull)banner SWIFT_WARN_UNUSED_RESULT;
/// Leaderboard banner size 728dp width and 90dp height
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, strong) CASSize * _Nonnull leaderboard;)
+ (CASSize * _Nonnull)leaderboard SWIFT_WARN_UNUSED_RESULT;
/// Medium Rectangle size 300dp width and 250dp height
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, strong) CASSize * _Nonnull mediumRectangle;)
+ (CASSize * _Nonnull)mediumRectangle SWIFT_WARN_UNUSED_RESULT;
/// Typically, Smart Banners on phones have a <code>banner</code> size.
/// Or on tablets a <code>leaderboard</code> size.
+ (CASSize * _Nonnull)getSmartBanner SWIFT_WARN_UNUSED_RESULT;
/// Inline adaptive banners are larger, taller banners compared to anchored adaptive banners.
/// They are of variable height, and can be as tall as the device screen.
/// <ul>
///   <li>
///     The height of adaptive banners cannot be less than 32 points.
///   </li>
///   <li>
///     The inline adaptive banners use fixed aspect ratios instead of fixed heights.
///   </li>
///   <li>
///     You must know the width of the view that the ad will be placed in,
///     and this should take into account the device width and any safe areas that are applicable.
///   </li>
///   <li>
///     The inline adaptive banner sizes are designed to work best when using the full available width.
///     In most cases, this will be the full width of the screen of the device in use.
///     Be sure to take into account applicable safe areas.
///   </li>
/// </ul>
+ (CASSize * _Nonnull)getInlineBannerWithWidth:(CGFloat)width maxHeight:(CGFloat)maxHeight SWIFT_WARN_UNUSED_RESULT;
/// Create Adaptive AdSize placed in container for current screen orientation.
/// <ul>
///   <li>
///     The height of adaptive banners cannot be less than 50 points and more than 250 points.
///   </li>
///   <li>
///     The adaptive banners use fixed aspect ratios instead of fixed heights.
///   </li>
/// </ul>
+ (CASSize * _Nonnull)getAdaptiveBannerInContainer:(UIView * _Nonnull)view SWIFT_WARN_UNUSED_RESULT;
/// Create Adaptive AdSize with window width for current orientation.
/// <ul>
///   <li>
///     The height of adaptive banners cannot be less than 50 points and more than 250 points.
///   </li>
///   <li>
///     The adaptive banners use fixed aspect ratios instead of fixed heights.
///   </li>
/// </ul>
+ (CASSize * _Nonnull)getAdaptiveBannerInWindow:(UIWindow * _Nonnull)inWindow SWIFT_WARN_UNUSED_RESULT;
/// Create Adaptive AdSize with Max Width for current screen orientation.
/// <ul>
///   <li>
///     The height of adaptive banners cannot be less than 50 points and more than 250 points.
///   </li>
///   <li>
///     The width of adaptive banners cannot be less than 300 points.
///   </li>
///   <li>
///     The adaptive banners use fixed aspect ratios instead of fixed heights.
///   </li>
/// </ul>
+ (CASSize * _Nonnull)getAdaptiveBannerForMaxWidth:(CGFloat)maxWidth SWIFT_WARN_UNUSED_RESULT;
- (CGSize)toCGSize SWIFT_WARN_UNUSED_RESULT;
@property (nonatomic, readonly) BOOL isAdaptive;
@property (nonatomic, readonly) BOOL isInline;
- (CASSize * _Nullable)findClosestSize SWIFT_WARN_UNUSED_RESULT;
/// Format: (width, height)
@property (nonatomic, readonly, copy) NSString * _Nonnull description;
@property (nonatomic, readonly) NSUInteger hash;
- (BOOL)isEqual:(id _Nullable)object SWIFT_WARN_UNUSED_RESULT;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end


@class NSNumber;

SWIFT_PROTOCOL_NAMED("NativeAdStarRating")
@protocol CASNativeAdStarRating
@property (nonatomic, strong) NSNumber * _Nullable rating;
@end


SWIFT_CLASS_NAMED("CASStarRatingView")
@interface CASStarRatingView : UIView <CASNativeAdStarRating>
@property (nonatomic, strong) NSNumber * _Nullable rating;
- (nonnull instancetype)initWithFrame:(CGRect)frame SWIFT_UNAVAILABLE;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)coder SWIFT_UNAVAILABLE;
- (void)layoutSubviews;
@property (nonatomic, readonly) CGSize intrinsicContentSize;
@end

enum CASGender : NSInteger;

SWIFT_CLASS_NAMED("CASTargetingOptions")
@interface CASTargetingOptions : NSObject
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
/// The user’s gender
- (void)setGender:(enum CASGender)gender;
/// The user’s gender
- (enum CASGender)getGender SWIFT_WARN_UNUSED_RESULT;
/// The user’s age
/// Limitation: 1-99 and 0 is ‘unknown’
- (void)setAge:(NSInteger)age;
/// The user’s age
- (NSInteger)getAge SWIFT_WARN_UNUSED_RESULT;
/// The user’s current location.
/// Location data is not used to CAS; however, it may be used by 3rd party ad networks.
/// Do not use Location just for advertising.
/// Your app should have a valid use case for it as well.
- (void)setLocationWithLatitude:(double)latitude longitude:(double)longitude;
/// Clear the user’s current location.
- (void)clearLocation;
/// Collect from the device the latitude and longitude coordinated truncated to the
/// hundredths decimal place.
/// Collect only if your application already has the relevant end-user permissions.
/// Does not collect if the target audience is children.
/// Disabled by default.
- (void)setLocationCollectionEnabled:(BOOL)enabled;
/// Collect from the device the latitude and longitude coordinated truncated to the
/// hundredths decimal place.
/// Collect only if your application already has the relevant end-user permissions.
/// Does not collect if the target audience is children.
/// Disabled by default.
- (BOOL)getLocationCollectionEnabled SWIFT_WARN_UNUSED_RESULT;
/// A list of keywords, interests, or intents related to your application.
/// Words or phrase describing the current activity of the user for targeting purposes.
- (void)setKeywords:(NSArray<NSString *> * _Nullable)keywords;
- (NSArray<NSString *> * _Nullable)getKeywords SWIFT_WARN_UNUSED_RESULT;
/// Sets the content URL for a web site whose content matches the app’s primary content.
/// This web site content is used for targeting and brand safety purposes.
/// Limitation: max URL length 512
- (void)setContentUrl:(NSString * _Nullable)url;
- (NSString * _Nullable)getContentUrl SWIFT_WARN_UNUSED_RESULT;
@end

typedef SWIFT_ENUM_NAMED(NSInteger, CASType, "CASType", open) {
  CASTypeBanner = 0,
  CASTypeInterstitial = 1,
  CASTypeRewarded = 2,
  CASTypeAppOpen = 3,
  CASTypeNative = 4,
  CASTypeNone = 5,
};


SWIFT_CLASS("_TtC18CleverAdsSolutions10CASTypeInt")
@interface CASTypeInt : NSObject
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly) NSUInteger none;)
+ (NSUInteger)none SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly) NSUInteger banner;)
+ (NSUInteger)banner SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly) NSUInteger interstitial;)
+ (NSUInteger)interstitial SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly) NSUInteger rewarded;)
+ (NSUInteger)rewarded SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly) NSUInteger native;)
+ (NSUInteger)native SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly) NSUInteger appOpen;)
+ (NSUInteger)appOpen SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly) NSUInteger everything;)
+ (NSUInteger)everything SWIFT_WARN_UNUSED_RESULT;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end

typedef SWIFT_ENUM_NAMED(NSInteger, CASGender, "Gender", open) {
  CASGenderUnknown = 0,
  CASGenderMale = 1,
  CASGenderFemale = 2,
};


/// Adapter initialization stack trace:
/// <ol>
///   <li>
///     [getVersionAndVerify]
///   </li>
///   <li>
///     [getRequiredVersion]
///   </li>
///   <li>
///     [prepareSettings] for each [MediationInfo] in waterfall
///   </li>
///   <li>
///     [isEarlyInit] when true call [initMain] immediately
///   </li>
///   <li>
///     [initBidding] for each [MediationInfo] in waterfall or [onMigrateToMediation]
///   </li>
///   <li>
///     [getVerifyError] stop flow if error returned
///   </li>
///   <li>
///     [initMain]
///   </li>
///   <li>
///     [onInitialized] callback after initialization done
///   </li>
///   <li>
///     [initBanner], [initInterstitial], [initRewarded] for each [MediationInfo] in waterfall
///   </li>
/// </ol>
SWIFT_CLASS_NAMED("MediationAdapter")
@interface CASMediationAdapter : NSObject
- (nonnull instancetype)init;
@end


/// Mediation agent request call stack
/// <ol>
///   <li>
///     If [isAdCached] return false
///   </li>
///   <li>
///     [requestAd]
///   </li>
///   <li>
///     Callback [onAdLoaded] OR [onAdFailedToLoad]
///   </li>
/// </ol>
/// Mediation agent impression call stack
/// <ol>
///   <li>
///     If [isAdCached] return true
///   </li>
///   <li>
///     [showAd]
///   </li>
///   <li>
///     Callback [onAdShown] OR [showFailed]
///   </li>
///   <li>
///     Callback [onAdClicked] when ad clicked
///   </li>
///   <li>
///     Callback [onAdCompleted] when ad video completed
///   </li>
///   <li>
///     Callback [onAdClosed]
///   </li>
///   <li>
///     [disposeAd]
///   </li>
/// </ol>
SWIFT_CLASS_NAMED("MediationAgent")
@interface CASMediationAgent : CASMediationUnit
- (BOOL)isAdCached SWIFT_WARN_UNUSED_RESULT;
- (void)toggleIgnoreMode;
@end


SWIFT_CLASS_NAMED("MediationBannerAgent")
@interface CASMediationBannerAgent : CASMediationAgent
- (BOOL)isAdCached SWIFT_WARN_UNUSED_RESULT;
@end

@class UIImage;
@class NSURL;

SWIFT_CLASS_NAMED("NativeAdContent")
@interface CASNativeAdContent : NSObject
@property (nonatomic, readonly, copy) NSString * _Nullable headline;
@property (nonatomic, readonly, copy) NSString * _Nullable body;
@property (nonatomic, readonly, copy) NSString * _Nullable callToAction;
@property (nonatomic, readonly, strong) UIImage * _Nullable icon;
@property (nonatomic, readonly, copy) NSURL * _Nullable iconURL;
@property (nonatomic, readonly, copy) NSString * _Nullable advertiser;
@property (nonatomic, readonly, copy) NSString * _Nullable store;
@property (nonatomic, readonly, copy) NSString * _Nullable price;
@property (nonatomic, readonly, strong) NSNumber * _Nullable starRating;
@property (nonatomic, readonly, copy) NSString * _Nullable reviewCount;
@property (nonatomic, readonly, copy) NSString * _Nullable adLabel;
@property (nonatomic, readonly) BOOL hasVideoContent;
@property (nonatomic, readonly) BOOL hasMediaContent;
@property (nonatomic, readonly) CGFloat mediaContentAspectRatio;
@property (nonatomic, readonly, strong) UIImage * _Nullable mediaImage;
@property (nonatomic, readonly, copy) NSURL * _Nullable mediaImageURL;
/// Reference to a root view controller that is used by the ad to present full screen content after
/// the user interacts with the ad. The root view controller is most commonly the view controller
/// displaying the ad.
@property (nonatomic, weak) UIViewController * _Nullable rootViewController;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS_NAMED("MediationNativeAdContent")
@interface CASMediationNativeAdContent : CASNativeAdContent
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@property (nonatomic, strong) UIViewController * _Nullable rootViewController;
@end














#endif
#if __has_attribute(external_source_symbol)
# pragma clang attribute pop
#endif
#if defined(__cplusplus)
#endif
#pragma clang diagnostic pop
#endif

#else
#error unsupported Swift architecture
#endif
