name: cleverads
moduleFolder: cleverads
artifactSource: latest release https://github.com/cleveradssolutions/CAS-iOS/releases, CleverAdsSolutions-x.x.x.x.zip from assets, unpack to CleverAdsSolutions
downloadLocation: ./.robopods-wip/CleverAdsSolutions/CleverAdsSolutions.xcframework
