name: facebook-core-basics
moduleFolder: facebook/ios-core-basics
artifactSource:
  - check if folder exists in ./.robopods-wip/Facebook/FBSDKCoreKit_Basics, stop and report error if not
downloadLocation: ./.robopods-wip/Facebook
