name: facebook-bom
moduleFolder: facebook/ios-bom
artifactSource:
  - check if folder exists in ~/Downloads/robopods-wip/Facebook/, stop and report error if not
downloadLocation: ~/Downloads/robopods-wip/Facebook
dropVersionSuffix: true
