name: facebook-login
moduleFolder: facebook/ios-login
artifactSource:
  - check if folder exists in ./.robopods-wip/Facebook/FBSDKLoginKit, stop and report error if not
downloadLocation: ./.robopods-wip/Facebook
