name: facebook-aemkit
moduleFolder: facebook/ios-aem
artifactSource:
  - check if folder exists in ./.robopods-wip/Facebook/FBAEMKit.xcframework, stop and report error if not
downloadLocation: ./.robopods-wip/Facebook
