name: firebase-messaging
moduleFolder: firebase/ios-messaging
artifactSource:
  - check if folder exists in ./.robopods-wip/Firebase/FirebaseMessaging/FirebaseMessaging.xcframework/, stop and report error if not
downloadLocation: ./.robopods-wip/Firebase
