name: firebase-remoteconfig
moduleFolder: firebase/ios-remoteconfig
artifactSource:
  - check if folder exists in ./.robopods-wip/Firebase/FirebaseRemoteConfig/FirebaseRemoteConfig.xcframework/, stop and report error if not
downloadLocation: ./.robopods-wip/Firebase
