name: firebase-storage
moduleFolder: firebase/ios-storage
artifactSource:
  - check if folder exists in ~/Downloads/robopods-wip/Firebase/FirebaseStorage/FirebaseStorage.xcframework/, stop and report error if not
downloadLocation: ~/Downloads/robopods-wip/Firebase
dropVersionSuffix: true
