name: firebase-core
moduleFolder: firebase/ios-core
artifactSource:
  - check if folder exists in ./.robopods-wip/Firebase/FirebaseAnalytics/FirebaseCore.xcframework/, stop and report error if not
downloadLocation: ./.robopods-wip/Firebase
