name: firebase-auth
moduleFolder: firebase/ios-auth
artifactSource:
  - check if folder exists in ./.robopods-wip/Firebase/FirebaseAuth/FirebaseAuth.xcframework/, stop and report error if not
downloadLocation: ./.robopods-wip/Firebase
