name: firebase-installations
moduleFolder: firebase/ios-installations
artifactSource:
  - check if folder exists in ~/Downloads/robopods-wip/Firebase/FirebaseAnalytics/FirebaseInstallations.xcframework/, stop and report error if not
downloadLocation: ~/Downloads/robopods-wip/Firebase
dropVersionSuffix: true
