name: firebase-installations
moduleFolder: firebase/ios-installations
artifactSource:
  - check if folder exists in ./.robopods-wip/Firebase/FirebaseAnalytics/FirebaseInstallations.xcframework/, stop and report error if not
downloadLocation: ./.robopods-wip/Firebase
