name: firebase-storage
moduleFolder: firebase/ios-storage
artifactSource:
  - check if folder exists in ./.robopods-wip/Firebase/FirebaseStorage/FirebaseStorage.xcframework/, stop and report error if not
downloadLocation: ./.robopods-wip/Firebase
