name: firebase-analytics
moduleFolder: firebase/ios-analytics
artifactSource:
  - check if folder exists in ./.robopods-wip/Firebase/FirebaseAnalytics/FirebaseAnalytics.xcframework/, stop and report error if not
downloadLocation: ./.robopods-wip/Firebase
