name: inmobi
moduleFolder: inmobi
artifactSource: download iOS sdk (for manual integration) from https://www.inmobi.com/sdk, unpack to InMobi-iOS-SDK
downloadLocation: ./.robopods-wip/InMobi-iOS-SDK/
