name: ironsource
moduleFolder: ironsource
artifactSource:
    - check latest release at https://github.com/ironsource-mobile/iOS-sdk/releases/
    - download IronSourceX.X.X.zip from assets
    - unpack it an move IronSource to ./.robopods-wip/
    - expected location ./.robopods-wip/IronSource/IronSource.xcframework
downloadLocation: ./.robopods-wip/IronSource/
